import = ["~/.config/alacritty/colors.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
#opacity = 0.9

[window.padding]
x = 25
y = 25

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "medium"
